# Question 1:
    
    Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [57]:
import numpy as np

# element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

arr1 = np.array([[2,5,6],[7,5,3]]) # creating array 1
print("Original Array 1:\n",arr1)

arr2 = np.array([[1,9,4],[5,7,3]]) # creating array 2
print("Original Array 2:\n",arr2)

# comparing array1 to array2 if arr1 element greater than array 2 element return true else return false
print('\n'"Greater number:\n",np.greater(arr1,arr2)) 

# comparing array1 to array2 if arr1 element greater than or equal to array 2 element return true else return false
print('\n'"greater_equal :\n",np.greater_equal(arr1,arr2)) 

# comparing array1 to array2 if arr1 element less than array 2 element return true else return false
print('\n'"less number :\n",np.less(arr1,arr2))

# comparing array1 to array2 if arr1 element less than or equal to array 2 element return true else return false
print('\n'"less equal :\n",np.less_equal(arr1,arr2))

Original Array 1:
 [[2 5 6]
 [7 5 3]]
Original Array 2:
 [[1 9 4]
 [5 7 3]]

Greater number:
 [[ True False  True]
 [ True False False]]

greater_equal :
 [[ True False  True]
 [ True False  True]]

less number :
 [[False  True False]
 [False  True False]]

less equal :
 [[False  True False]
 [False  True  True]]


# Question 2:
    Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [30]:
# create an array of 10 zeros,10 ones, 10 fives

print("Array of 10 zeros :",np.zeros(10)) # creating zeros array using zeros function
print("Array of 10 Ones  :",np.ones(10))  # creating ones array using ones function
print("Array of 10 fives :",np.ones(10)*5) # creating of 10 fives  using multiplication method (multiply by ones element)

Array of 10 zeros : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 Ones  : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives : [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# Question 3: 
    Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [56]:
# sum of each column and sum of each row of a given array

x = np.arange(1,5).reshape(2,2) # creating array 1
print("array1:\n",x)

y = np.arange(1,5).reshape(2,2) # creating array 2
print("\narray2:\n",x)

print("\nSum of each column",np.sum(x,axis=0)) # sum of each column

print("\nSum of each Rows",np.sum(x,axis=1)) # sum of each rows

array1:
 [[1 2]
 [3 4]]

array2:
 [[1 2]
 [3 4]]

Sum of each column [4 6]

Sum of each Rows [3 7]


# Question 4: 
    Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [72]:
#program to add, subtract, multiply, divide arguments element-wise.

arr_1=np.array([[2,5],[8,6]]) 
arr_2=np.array([[5,9],[3,7]])
print("array 1:\n",arr_1)
print("\narray 2:\n",arr_2)

print("\nAddition of array:\n",np.add(arr1,arr2))          # addition of array 1 to array 2 using add function
print("\nSubtraction of array:\n",np.subtract(arr1,arr2))  # subtract of array 1 to array 2 using subtract function
print("\nMultiplication of array:\n",np.multiply(arr1,arr2)) # multiply of array 1 to array 2 using multiply function
print("\nDivision of array:\n",np.divide(arr1,arr2))        # divide array 1 to array 2 using divide function

array 1:
 [[2 5]
 [8 6]]

array 2:
 [[5 9]
 [3 7]]

Addition of array:
 [[ 3 14 10]
 [12 12  6]]

Subtraction of array:
 [[ 1 -4  2]
 [ 2 -2  0]]

Multiplication of array:
 [[ 2 45 24]
 [35 35  9]]

Division of array:
 [[2.         0.55555556 1.5       ]
 [1.4        0.71428571 1.        ]]


# Question 5: 
    Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in deg

In [90]:
#program to compute the trigonometric sine, cosine and tangent array of angles given in deg

#compute trignometry sine given degree using sin function
print("Sine Array of angles given degree:\n",np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.)) 

#compute trignometry cosine given degree using cos function
print("\nCosine Array of angles given degree:\n",np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

#compute trignometry tangent given degree using tan function
print("\nTangent Array of angles given degree:\n",np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

Sine Array of angles given degree:
 [0.         0.5        0.70710678 0.8660254  1.        ]

Cosine Array of angles given degree:
 [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

Tangent Array of angles given degree:
 [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


# Question 6: 
    Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels

In [92]:
# program to create and display a DataFrame from a specified dictionary data which has the index labels

import numpy as np
import pandas as pd

emp_data = {"EmpID":[1011,1012,1013,1014],"Emp_Name":['Akshay','Vilas','sharath','Nivas'],"Salary":[40000,35000,45000,75000]}

labels = ['A','V','S','N']

df = pd.DataFrame(emp_data , index=labels)
print(df)

   EmpID Emp_Name  Salary
A   1011   Akshay   40000
V   1012    Vilas   35000
S   1013  sharath   45000
N   1014    Nivas   75000


# Question 7: 
    Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [98]:
import numpy as np
import pandas as pd

Exam_Data = {"Student_Name":['Sahil','Amar','Asha','Karan'],
            "Division":['A','A','B','C'],
            "Score":[75.3,63.49,78.00,87.25]}

df = pd.DataFrame(Exam_Data)
print("Student Exam Score Report:\n",df)

print("\nSelected Name and Score:\n",df[['Student_Name','Score']])



Student Exam Score Report:
   Student_Name Division  Score
0        Sahil        A  75.30
1         Amar        A  63.49
2         Asha        B  78.00
3        Karan        C  87.25

Selected Name and Score:
   Student_Name  Score
0        Sahil  75.30
1         Amar  63.49
2         Asha  78.00
3        Karan  87.25


# Question 8:
    Write a Pandas program to join the two given dataframes along rows and assign all data.

In [99]:
student_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'], 
        'marks': [200, 210, 190, 222, 199]})

student_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'], 
        'marks': [201, 200, 198, 219, 201]})

print("Original DataFrames:")
print(student_data1)
print("-------------------------------------")
print(student_data2)
print("\nJoin the said two dataframes along rows:")
result_data = pd.concat([student_data1, student_data2])
print(result_data)

Original DataFrames:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
-------------------------------------
  student_id              name  marks
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201

Join the said two dataframes along rows:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201


# Question 9:
    Write a Pandas program to detect missing values of a given DataFrame. Display True or False

In [118]:
import numpy as np
import pandas as pd

emp_data = {"EmpID":[1011,1012,1013,1014],"Emp_Name":['Akshay','Vilas','sharath','Nivas'],"Salary":[40000,35000,45000,75000]}

labels = ['A','V','S','N']

df = pd.DataFrame(emp_data , index=labels)
print("Original Data:\n",df)

print("\nmissing values of a given DataFrame:\n",df.isna())




Original Data:
    EmpID Emp_Name  Salary
A   1011   Akshay   40000
V   1012    Vilas   35000
S   1013  sharath   45000
N   1014    Nivas   75000

missing values of a given DataFrame:
    EmpID  Emp_Name  Salary
A  False     False   False
V  False     False   False
S  False     False   False
N  False     False   False


# Question 10:
    Write a Pandas program to create and display a one-dimensional array-like object containing an array of data.

In [116]:
import pandas as pd
ds = pd.Series(['Ashish','','Sam',85])
print(ds)

0    Ashish
1          
2       Sam
3        85
dtype: object
